
### Get All Courses
GET http://localhost:5000/api/courses
Content-Type: application/json

### Get Course By courseID
GET http://localhost:5000/api/courses/6058c17a33ae204dd0322c66
Content-Type: application/json


### Get all courses by spcific Student
GET http://localhost:5000/api/coursesByStudent/6058ee6a7c08dc520c92e2a7
Content-Type: application/json

