POST http://localhost:5000/create
Content-Type: application/json

{   "studentNumber" : 1,
    "firstName" : "Sergio",
    "lastName" : "Silva",
 	"address" : "test",
 	"city": "test",
    "phoneNumber": 6475737563,
    "email": "s@hotmail.com",
    "program": "IT",
    "password": "admin"
}